# Generated by Django 5.2.7 on 2025-10-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(unique=True)),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
